export { default as Hero } from './Hero.js'
export { default as Features } from './Features.js'
export { default as Pricing } from './Pricing.js'
export { default as CTA } from './CTA.js'
export { default as Contact } from './Contact.js'
export { default as Reviews } from './Reviews.js'